In [4]:
import numpy as np

# 1. Tạo mảng arr có 6 phần tử
arr = np.array([0, 1, 2, 3, 4, 5])
print("arr:", arr)

# 2. Tạo mảng 2D 3x3 với giá trị từ 0 → 8
arr_2D = np.arange(9).reshape(3, 3)
print("arr_2D:\n", arr_2D)

# 3. Ghép arr và arr_2D (chuyển arr thành hàng trước)
arr_row = arr.reshape(2, 3)
new_arr = np.vstack((arr_row, arr_2D))
print("Ghép mảng:\n", new_arr)

# 4. Đảo ngược cột của mảng 2D
print("Đảo ngược cột:\n", arr_2D[:, ::-1])

# 5. Chuyển hàng thành cột (chuyển vị)
print("Chuyển vị:\n", arr_2D.T)

# 6. Tạo mảng có phần tử NaN
arr_null = np.array([[1, 2, 3], [np.nan, 9, 4], [5, 6, 7]])
print("arr_null:\n", arr_null)

# 7. Kiểm tra phần tử NaN
print("Các phần tử là NaN:\n", np.isnan(arr_null))
print("Tổng số phần tử NaN:", np.isnan(arr_null).sum())

arr: [0 1 2 3 4 5]
arr_2D:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Ghép mảng:
 [[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
Đảo ngược cột:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]
Chuyển vị:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
arr_null:
 [[ 1.  2.  3.]
 [nan  9.  4.]
 [ 5.  6.  7.]]
Các phần tử là NaN:
 [[False False False]
 [ True False False]
 [False False False]]
Tổng số phần tử NaN: 1
